# Generated by Django 5.0.3 on 2024-03-13 10:29

import ExtendingUserModel.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
            ],
            bases=(ExtendingUserModel.web.models.AuditModel, models.Model),
        ),
    ]
