# Generated by Django 5.0.3 on 2024-04-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('pages', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Science-Fiction', 'Sciencefiction'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Action', 'Action')], max_length=15)),
            ],
        ),
    ]
